### ISSUE TITLE
Add dependency management

### ISSUE THREAD

**Issue by brettcave** [splunk/splunk-library-javalogging#1]
Adding in dependency management would be great, so that artifacts can be published to a repository and pulled in via Maven / Ivy / SBT.

E.g, a maven pom: 

    <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.dtdsoftware.splunk.logging</groupId>
      <artifactId>splunklogging</artifactId>
      <version>0.3.0</version>
      <description>Splunk Logging API (TCP Raw and REST)</description>
      <dependencies>
        <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
          <version>1.6.4</version>
        </dependency>
      </dependencies>
    </project>

**Comment by leon-barrett** [comment]
Should this issue be closed? The aforementioned pull request was merged.
