### ISSUE TITLE
Add license information in pom.xml and in jar file

### ISSUE THREAD

**Issue by vespasien** [splunk/splunk-library-javalogging#10]
Hi guys,

Can you please add license information in your your maven's pom.xml and in the jar. 

This will allow me to use maven license plugin properly on my project.

Thanks,

Will.

**Comment by shakeelmohamed** [comment]
Hi @Willdon,

Would you mind outlining specifically what needs to be changed? We're open to a pull request to the `develop` branch if you already know how to fix our setup.

Thanks
