### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by pebo** [splunk/splunk-library-javalogging#103]
The pom files add gson as compile scoped dependency even though it's only used during tests.

I've tried to fix this and some other issues in https://github.com/splunk/splunk-library-javalogging/pull/105

But are even the log4j a dependencies supposed to be in compile scope or can that be change to provided e.g.

```
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.1</version>
            <scope>provided</scope>
        </dependency>
```

With the current pom file we need to exclude log4j and gson to avoid bundling them with our app.

**Comment by pebo** [comment]
I've added another pull request to fix log4j dependency and avoid reexporting junit and hamcrest in compile scope: https://github.com/splunk/splunk-library-javalogging/pull/106

**Comment by mvdobrinin** [comment]
@shakeelmohamed @fantavlik Any chance of movement on this issue? 

Running into some issues due to the log4j dependency when consuming this artifact. It seems like many of the logging dependencies were added just for the unit tests as part of f3f780cea2586f798dccc15541d94bce12745ef6 by @madhadron, but these could be set to test or provided scope.

**Comment by shakeelmohamed** [comment]
@mvdobrinin we're open to a pull request, but the team does not have any bandwidth to dedicate to this issue at the moment.

**Comment by mvdobrinin** [comment]
@shakeelmohamed I think #106 addresses this issue. I will try to rebase it to fix merge conflicts.

**Comment by mvdobrinin** [comment]
@shakeelmohamed #124 seems to do the trick
