### ISSUE TITLE
Splunk HEC Log4j2 configuration

### ISSUE THREAD

**Issue by sivaviaan** [splunk/splunk-library-javalogging#104]
Hi,

While using log4j2 configuration for Splunk HEC, i had to make couple of changes for it to work.

1. The url that is mentioned in the configuraiton example
[https://github.com/splunk/splunk-library-javalogging/blob/master/src/test/resources/log4j2.xml]
points to   url="http://localhost:5555/services/collector/event/1.0" and if i do the same configuration, i found it is appending the following path   private static final String HttpEventCollectorUriPath = "/services/collector/event/1.0".

So ideally the test sample should change to something like just till host port and not the entire path.
This took me a long time to figure out and i had to put the logs in the library as i was running this instance in the cloud

2.The way splunk cloud was set in my case was without the version number i.e.1.0 was not included in that . This was also another issue where as the path that gets appended as 1.0

3. HEC token was configured with no timestamp but the code was adding time as one of the parameters in json and it was not working for us.

**Comment by shakeelmohamed** [comment]
Hi @sivaviaan thanks for your feedback!

1. See #119 
2. Is this still an issue for you? If so, that's an easy change and will be fully backwards compatible to all other Splunk Cloud and Splunk Enterprise users.
3. What exactly was not working?

**Comment by fantavlik** [comment]
Closing per https://github.com/splunk/splunk-library-javalogging/pull/119
