### ISSUE TITLE
1.7.1 not available on Maven

### ISSUE THREAD

**Issue by siemelnarantact** [splunk/splunk-library-javalogging#108]
This is similar to https://github.com/splunk/splunk-library-javalogging/issues/90

Maven central says latest version is https://mvnrepository.com/artifact/com.splunk.logging/splunk-library-javalogging but when you click on that link it says "Note: There is a new version for this artifact" with a link to 1.7.1.

But when you add the dependency lines to build.gradle there is an error

```
* What went wrong:
Execution failed for task ':flywayMigrate'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not find com.splunk.logging:splunk-library-javalogging:1.7.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/splunk/logging/splunk-library-javalogging/1.7.1/splunk-library-javalogging-1.7.1.pom
       - https://repo.maven.apache.org/maven2/com/splunk/logging/splunk-library-javalogging/1.7.1/splunk-library-javalogging-1.7.1.jar
     Required by:
         project :
```

https://repo.maven.apache.org/maven2/com/ does not even have splunk in it.

**Comment by i2sheri** [comment]
http://splunk.jfrog.io/splunk/ext-releases-local/com/splunk/logging/splunk-library-javalogging/

**Comment by shakeelmohamed** [comment]
Hi @siemelnarantact, 

The artifacts published at this URL are not official, and not published by us. https://mvnrepository.com/artifact/com.splunk.logging/splunk-library-javalogging.

You will need to configure our maven repository like @i2sheri has pointed out, see the documentation for doing that here: http://dev.splunk.com/view/splunk-logging-java/SP-CAAAE3P

**Comment by cristianrgreco** [comment]
The documentation shared above (http://dev.splunk.com/view/splunk-logging-java/SP-CAAAE3P) says to add this maven repository:

```
<repository> 
  <id>splunk-artifactory</id> 
  <name>Splunk Releases</name> 
  <url>https://splunk.jfrog.io/splunk/ext-releases-local</url> 
</repository> 
```

But the artefact doesn't exist anymore in this repository. Where is the official jar being made available?

**Comment by vdiravka** [comment]
> The documentation shared above (http://dev.splunk.com/view/splunk-logging-java/SP-CAAAE3P) says to add this maven repository:
> 
> ```
> <repository> 
>   <id>splunk-artifactory</id> 
>   <name>Splunk Releases</name> 
>   <url>https://splunk.jfrog.io/splunk/ext-releases-local</url> 
> </repository> 
> ```
> 
> But the artefact doesn't exist anymore in this repository. Where is the official jar being made available?

I've faced with the same issue. It prevents other projects with this repository to get Build Successful result. So the issue is important!

**Comment by vdiravka** [comment]
https://splunk.jfrog.io/splunk/ext-releases-local
is available again
