### ISSUE TITLE
HttpEventCollectorSender does not pass the failed list of log events in case of error

### ISSUE THREAD

**Issue by bruderol** [splunk/splunk-library-javalogging#110]
https://github.com/splunk/splunk-library-javalogging/blob/5842663bbd507b0ec97783fc6b7bb514780abf9c/src/main/java/com/splunk/logging/HttpEventCollectorSender.java#L352

Obviously this line passes the wrong list of events in case of error (e.g. timeout) - `eventsBatch` is the field from the sender which is there to collect the next batch of events to be sent - which is not the list that has been failed to be sent (from final param) - which would be the final param `events` (as used in `completed` correctly).

Please fix this to pass the right value on error.

**Comment by shakeelmohamed** [comment]
Hi @bruderol thanks for the bug report,
I am very sorry that no one on the team got back to you.
I will be making a PR for this today.

**Comment by shakeelmohamed** [comment]
Fixed with #118
