### ISSUE TITLE
Log4j2 Appender Doesn't Close Properly

### ISSUE THREAD

**Issue by kgrabowski** [splunk/splunk-library-javalogging#115]
After adding the `HttpEventCollectorLog4jAppender` to the project, my app hangs indefinitely after finishing execution because the appender is not closed correctly.

Calling `LogManager.shutdown()` does not help, since `HttpEventCollectorLog4jAppender` overrides the `LifeCycle::stop()` method, which never gets called by the `LoggerContext`. Since the `HttpEventCollectorLog4jAppender` indirectly implements the `LifeCycle2` interface, the `LifeCycle2::stop(long, TimeUnit)` method is called instead (see `LoggerContext::stop(long, TimeUnit)`, which is called indirectly by the `LogManger::shutdown()` method).

Calling the `stop()` method on the `HttpEventCollectorLog4jAppender` "solves" the issue but also presents problems, since the shutdown doesn't wait for the async post to complete. If there is a log statement right before calling the `stop()` method, this message will not be logged to Splunk.

Sample code:

```
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.LoggerContext;

public class Program {
    private static final Logger logger = LogManager.getLogger(Program.class);

    public static void main(String[] args) {
        logger.info("This won't get logged to Splunk");
        LoggerContext.getContext(false)
                .getRootLogger()
                .getAppenders()
                .forEach((name, appender) -> appender.stop());
    }
}
```

The only way to truly shut down the app correctly is by adding `Thread.sleep(1000);` before the call to `stop()`. This is hacky at best.

*Note:* My use case is an Apache Spark job, so it has to terminate in a timely manner.

**Comment by shakeelmohamed** [comment]
@kgrabowski which version of the library are you using?

**Comment by kgrabowski** [comment]
@shakeelmohamed tested this with `splunk-library-javalogging` version `1.7.3` and Log4j2 version `2.10.0`

**Comment by dominikjungo** [comment]
got the same issue with log4j2 version 2.8.
I'd expect that no code in the application using the splunk-library is needed to shut it down/stop it correctly.
Also tried: 
- LogManager.shutdown(), see: https://logging.apache.org/log4j/2.0/faq.html#shutdown. No success
- Wrapping kgrabowski's solution an a jvm shutdown hook. No success

**Comment by kgrabowski** [comment]
@dominikjungo I wouldn't expect a JVM shutdown hook to execute at all, since the appender spawns a non-deamon thread that will keep the JVM running forever

**Comment by Dwapayan** [comment]
I am also having this same issue. I tried the 1.7.2 and got the same issue. When 1.7.2 library is added just the declaration causes program to keep running

private static Logger LOGGER = LogManager.getLogger(LoggerTest.class);

**Comment by theclish** [comment]
`HttpEventCollectorLog4jAppender` should override `boolean stop(final long timeout, final TimeUnit timeUnit)` instead of `void stop()`, which can then cancel its timer thread and allow the app to exit.

**Comment by shakeelmohamed** [comment]
@theclish can you make a PR for this change?

**Comment by theclish** [comment]
Yes and no. I can't authenticate during push of my branch. The code change is simple, replace the `void stop()` method override with

```
    @Override
    public boolean stop(final long timeout, final TimeUnit timeUnit) {
        this.sender.close();
        return super.stop(timeout, timeUnit);
    }
```
I still had to LogManager.shutdown() to make the appenders stop, but at least this allows it to happen.

**Comment by shakeelmohamed** [comment]
@theclish you'll want to fork the repo and create a pull request from your fork to this repo. These guides should help:

1. https://help.github.com/en/articles/fork-a-repo
2. https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by theclish** [comment]
thanks. https://github.com/splunk/splunk-library-javalogging/pull/122

**Comment by pattad** [comment]
Version 1.9.0 is also not sending all messages, when Java exits. I could solve the issue, by calling 
`LoggerContext.getContext(false).stop();`
before the application shuts down. Hereby, all log messages are sent to splunk.

**Comment by bparmar-splunk** [comment]
@kgrabowski,
This issue has already been taken care in above PR. 

Hence closing this issue.
Please let us know in case of any further queries.
Thank you.
