### ISSUE TITLE
Suggestion: deprecate <layout> in favour of  <encoder>  in TcpAppender

### ISSUE THREAD

**Issue by ls-urs-keller** [splunk/splunk-library-javalogging#126]
It seems that OutputStreamAppender (console, file, etc) have deprecated the 
`<layout>` element. To make the config consistent with those appenders it could make sense to do the same in TcpAppender.

**Comment by shakeelmohamed** [comment]
@urs-ikentoo-com we're open to a pull request if you'd like to make this change

**Comment by bparmar-splunk** [comment]
HI @ls-urs-keller,
Changes suggested by you are added in current working branch. Check this [commit](https://github.com/splunk/splunk-library-javalogging/commit/5675cc098ac3a1560155dfcdaaef4811a17218f2).

It will be available in next java logging release.

Closing this ticket for now.
Please let us know in case of any further queries.

**Comment by davidkarlsen** [comment]
What about the HttpEventCollectorLogbackAppender ?
