### ISSUE TITLE
Handling of queue size overflow?

### ISSUE THREAD

**Issue by blackside** [splunk/splunk-library-javalogging#129]
We have noticed that when we have overflow in the queue (queue is full = @code false)
Loggdata just gets thrown away and no information is presented that indicates overflow.

Is this intended behaviour? Or am I missing something?

I would love to have some sort of indication logged that the queue size have been reached.

```
/**
     * Inserts the specified element into this queue if it is possible to do
     * so immediately without violating capacity restrictions, returning
     * {@code true} upon success and {@code false} if no space is currently
     * available.  When using a capacity-restricted queue, this method is
     * generally preferable to {@link #add}, which can fail to insert an
     * element only by throwing an exception.
     *
     * @param e the element to add
     * @return {@code true} if the element was added to this queue, else
     *         {@code false}
     * @throws ClassCastException if the class of the specified element
     *         prevents it from being added to this queue
     * @throws NullPointerException if the specified element is null
     * @throws IllegalArgumentException if some property of the specified
     *         element prevents it from being added to this queue
     */
    boolean offer(E e); 
```

**Comment by bparmar-splunk** [comment]
Hi @blackside,
Thanks for reaching out.
 
Could you please elaborate on this issue?
It would help us in troubleshooting into more detail.

Also, we are made several releases since this issue posted. We would recommend you to update logging library to newer version [1.11.6](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.6) and re-validate your use-case.

**Comment by bparmar-splunk** [comment]
Hi @blackside,
We have not heard any update regarding your issue.

We are closing this issue for now.
Please let us know if you have any further issues.

Thank you.
