### ISSUE TITLE
Batch size count issue

### ISSUE THREAD

**Issue by tejadivvi** [splunk/splunk-library-javalogging#137]
Hi, 

With increase of batch size count to 20 and batch size bytes to 20Kb, i see the events are dropping in Splunk. Anyone faced this issue earlier? 
Thanks
Teja

**Comment by akauppi** [comment]
@tejadivvi I am working with similar situations.

Your message contains way too little information for people to reply. What do you mean by dropping - that you lose events in the flight?

Please share more if the issue is still valid, or ask it to be closed if it's not. Thank you.

**Comment by bparmar-splunk** [comment]
Hi @tejadivvi,
Since there is no updates for this issue. Assuming it as resolved for now.

Please let us know, if you still face any issue.

Closing this issue.
