### ISSUE TITLE
Version 1.8.0 is not compatible with Log4j 2.11.x

### ISSUE THREAD

**Issue by damiancalabresi** [splunk/splunk-library-javalogging#147]
Hi,

The version 1.8.0 of the Log4j HEC Appender use a constructor of the AbstractAppender that has been added in the version 2.13.x, sending the Property constant "EMPTY_ARRAY".

At startup, it throws the exception:

java.lang.NoSuchFieldError: EMPTY_ARRAY

Please, this should be specified in the changelog.

**Comment by fantavlik** [comment]
Good point @damiancalabresi sorry for omitting this, I've added to the Release Notes in Github indicating the logging library updates:

https://github.com/splunk/splunk-library-javalogging/releases/tag/1.8.0
