### ISSUE TITLE
Timer initiated in HttpEventCollectorSender is not a daemon

### ISSUE THREAD

**Issue by atoulme** [splunk/splunk-library-javalogging#149]
The Timer created in HttpEventCollectorSender is not a daemon.

As result, programs will not exit when done, waiting on the timer to finish.

**Comment by shakeelmohamed** [comment]
Thanks @atoulme, we merged the PR. How urgently do you need a release with the fix?

**Comment by atoulme** [comment]
I found a workaround by avoiding to create the appender, so no rush for a fix.

**Comment by fireflo** [comment]
Hi! Would it be possible to have this released?
Thank you!

**Comment by bparmar-splunk** [comment]
PR is being merged and changes exist in current [release](https://github.com/splunk/splunk-library-javalogging/blob/1.11.5/src/main/java/com/splunk/logging/HttpEventCollectorSender.java#L156).

Hence, closing this issue.
