### ISSUE TITLE
Upgrade to work with logback 1.1.3

### ISSUE THREAD

**Issue by colsson11** [splunk/splunk-library-javalogging#15]
Is there a plan to upgrade to logback 1.1.3? This has some method type signature changes and is thus incompatible with the currently compiled 1.5.0. The change in this project would just be to update the compile time dependencies in pom.xml, but it would obviously be backwards incompatible.

Specifically, the issue I see is with the change of the method

    ch.qos.logback.core.net.DefaultSocketConnector.DefaultSocketConnector(InetAddress, int, int, int)

to

    ch.qos.logback.core.net.DefaultSocketConnector.DefaultSocketConnector(InetAddress, int, long, long)

which is called in
    
    com.splunk.logging.TcpAppender

Thanks,

Christian

**Comment by shakeelmohamed** [comment]
Hi @colsson11,

Thanks for bringing this to our attention.
We are open to a pull request against the `develop` branch if we can maintain backward compatibliity with logback 1.0.13.
Please let us know if you have any questions!

**Comment by colsson11** [comment]
Thanks @shakeelmohamed , have created a pull request.

https://github.com/splunk/splunk-library-javalogging/pull/16

Cheers,

Christian

**Comment by colsson11** [comment]
Hi @shakeelmohamed , will you be able to merge this? Let me know if you need any more info or changes etc.

Cheers,

Christian

**Comment by shakeelmohamed** [comment]
Hi @colsson11, we appreciate the follow up! We will get you some feedback this week

**Comment by shakeelmohamed** [comment]
#16 has been merged, we will need to do some manual testing before releasing the changes.

**Comment by shakeelmohamed** [comment]
This was fixed in v1.5.1 a while back
