### ISSUE TITLE
Async flush and batch calls are preventing completely sending all logs

### ISSUE THREAD

**Issue by mvaal** [splunk/splunk-library-javalogging#152]
This issue arrises when you have a container or lambda that is terminating immediately after app completion.

I submitted this as a partial solution: 
https://github.com/splunk/splunk-library-javalogging/pull/151

However, we are running into further issues with lambdas as the context is cached and stopping the appender is preventing new lambdas from logging.

Some refactoring needs to be done to allow a wait on so that all events have been sent and are currently no longer in flight in the OkHttpClient execution context so we can guarantee all messages are sent before lambda or container termination.

**Comment by snorwin** [comment]
@mvaal can you please test if the suggested solution in #179 does resolve your issues?

**Comment by stevejagodzinski** [comment]
Is there any configuration needed from the client application side besides upgrading to 1.11.0 to ensure that logs are not lost when running in lambda?

**Comment by bparmar-splunk** [comment]
Hi All,
Closing this issue as PRs for this issue are merged.

Thanks.
