### ISSUE TITLE
Unable to post events to HTTP Event Collector using spark logging library

### ISSUE THREAD

**Issue by pooja-murarka** [splunk/splunk-library-javalogging#158]
Followed steps as mentioned in blog: https://dev.splunk.com/enterprise/docs/java/logging-java/howtouseloggingjava/enableloghttpjava

But while running code on server unable to push data to HTTP Event Collector.
I tried using log4j2 and java.util.logging and code executes without any error.

Also, I am able to run below command successfully from server:

curl -k "http://host:8088//services/collector/event/1.0" -H "Authorization: Splunk token" -d '{"event": "Hello, world!", "sourcetype": "manual"}'

Below is the code:

public static void main(String[] args) {
         Logger logger = java.util.logging.Logger.getLogger("splunkLogger");

         String conf = "handlers=com.splunk.logging.HttpEventCollectorLoggingHandler\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.url=http://host:8088\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.token=token\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.batch_size_count=0\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.level=INFO\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.batch_size_bytes=1\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.batch_interval=0\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.disableCertificateValidation=true\n" +
           // "com.splunk.logging.HttpEventCollectorLoggingHandler.middleware=HttpEventCollectorUnitTestMiddleware\n" +
            "com.splunk.logging.HttpEventCollectorLoggingHandler.sourcetype=syslog\n" +
                 "com.splunk.logging.HttpEventCollectorLoggingHandler.include_logger_name=false\n" +
                 "com.splunk.logging.HttpEventCollectorLoggingHandler.include_thread_name=false\n" +
                 "com.splunk.logging.HttpEventCollectorLoggingHandler.include_exception=false\n" ;
         try {
            LogManager.getLogManager().readConfiguration(new ByteArrayInputStream(conf.getBytes()));
        } catch (IOException e) {
            System.out.println(e);
        }
        System.out.println(LogManager.getLogManager().getLogger("splunkLogger"));
         logger.setLevel(Level.INFO);
         String jsonMsg = String.format("{EventDate:%s, EventMsg:'this is a test event for java logging1}", new Date().toString());
         logger.info(jsonMsg);
        
         // logger.error("This is a test error for Logback test");

     }

**Comment by bparmar-splunk** [comment]
Hi @pooja-murarka,
Thank you for reaching out !

As per your above code, there are few things identified which might be the reason for failure to send logs to Splunk server: 

- URL should be proper (based on the Global Settings of Splunk HEC - Either http/https) and host should be replaced with your actual host.
- Token should be an alphanumeric UUID containing 36 characters. [This HEC token has to be created from Splunk UI. Refer [docs](https://docs.splunk.com/Documentation/Splunk/latest/Data/UsetheHTTPEventCollector#Configure_HTTP_Event_Collector_on_Splunk_Enterprise)]
- Batch size count should be greater than 0. (Check Info note on [docs](https://dev.splunk.com/enterprise/docs/devtools/java/logging-java/howtouseloggingjava/enableloghttpjava/#Configure-Logback))
- While setting up HEC token, you should select default index, if not then do specify it as an attribute such as:
    "com.splunk.logging.HttpEventCollectorLoggingHandler.index=main"

Please modify your code based on above changes and re-evaluate your test.
Please let us know if you still face any issues.

Thank you.

**Comment by bparmar-splunk** [comment]
Hi @pooja-murarka,
We assume that the issue you are facing will be closed based on above [comment](https://github.com/splunk/splunk-library-javalogging/issues/158#issuecomment-1209338062).

We are closing this ticket for now.
Please let us know in case of further queries.
Thank you !
