### ISSUE TITLE
splunk.artifactoryonline.com certificate has expired

### ISSUE THREAD

**Issue by panderso01** [splunk/splunk-library-javalogging#161]
Cannot download artifacts because the certificate has expired
![Screen Shot 2020-09-11 at 10 38 02 AM](https://user-images.githubusercontent.com/10248571/92956006-039aea80-f41b-11ea-8082-7810bf47d2b4.png)

**Comment by panderso01** [comment]
Is there an alternate repository we should use to get splunk-library-javalogging?

**Comment by ppyzik** [comment]
I can confirm that I have the same issue.

```
> Could not resolve all files for configuration ':deployment:runtimeClasspath'.
   > Could not download splunk-library-javalogging-1.7.3.jar (com.splunk.logging:splunk-library-javalogging:1.7.3)
      > Could not get resource 'https://splunk.artifactoryonline.com/artifactory/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.7.3/splunk-library-javalogging-1.7.3.jar'.
         > Could not GET 'https://splunk.artifactoryonline.com/artifactory/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.7.3/splunk-library-javalogging-1.7.3.jar'.
            > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

Any workarounds?

**Comment by CraccoMan** [comment]
i changed pom.xml like this

<repositories>
        <repository>
            <id>splunk-artifactory</id>
            <name>Splunk Releases</name>
            <url>https://splunk.jfrog.io/splunk/ext-releases-local</url>
        </repository>
    </repositories>

**Comment by bparmar-splunk** [comment]
Hi @panderso01,
This issue has been resolved by this [message](https://github.com/splunk/splunk-library-javalogging/issues/161#issuecomment-704342104).

Hence, closing this issue.
