### ISSUE TITLE
Documentation for batch_x

### ISSUE THREAD

**Issue by CoryKniefel** [splunk/splunk-library-javalogging#164]
Hello! 

I'm trying to find documentation on the 'batch_" properties in this example: https://github.com/splunk/splunk-library-javalogging/blob/master/src/test/resources/log4j2.xml

Can you point me in the right direction? 

Thanks!

**Comment by bparmar-splunk** [comment]
Hi @CoryKniefel,
Please find below details of batch* attributes:

  **batch_interval**: The interval, in milliseconds, at which to send batched events.
  **batch_size_count**: The maximum number of events to send per batch.
  **batch_size_bytes**: The maximum size, in bytes, of each batch of events.

Hope this information helps.
Closing this ticket for now.

Please let us know in case of further queries.
