### ISSUE TITLE
HttpEventCollectorLog4jAppender ignoreExceptions attribute is false by default and can't be set to true

### ISSUE THREAD

**Issue by macrergate** [splunk/splunk-library-javalogging#168]
Default value of ignoreExceptions  should be true, but it's false. 
Moreover, setting ignoreExceptions="true" in the config doesn't work. it's real value will be false.

Can be reproduced easily:
```
@Test
    public void ignoreExceptions() {
        final LoggerContext ctx = (LoggerContext) LogManager.getContext();
        final Configuration config = ctx.getConfiguration();
        HttpEventCollectorLog4jAppender appender = config.getAppender("http-input");

        Assert.assertTrue(appender.ignoreExceptions());
    }
```

**Comment by bparmar-splunk** [comment]
Hi @macrergate,
We did not hear anything from you regarding this issue.

We are closing this issue for now.
Please let us know in case of any further queries.

Thank you.
