### ISSUE TITLE
Bintray EOS affecting splunk?

### ISSUE THREAD

**Issue by thomas-weinstein-bosch** [splunk/splunk-library-javalogging#170]
Hello,

will the end of service for bintray, jcenter etc, affect the distribution of this lib in any way?
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Thank you in advance.

**Comment by zenmoto** [comment]
It shouldn't from what we know now- splunk.jfrog.io should continue to be available.
