### ISSUE TITLE
Change in the "sending raw events" behavior in version 1.9.0

### ISSUE THREAD

**Issue by yuemsike** [splunk/splunk-library-javalogging#177]
Hello,

we are using Splunk logging library to send message processing logs in SCI to Splunk HEC.
In the version 1.8.0 of Splunk logging library we implemented this with the log-type 'raw' and on this basis the library produced an event structure as follows:
{
"event":
  {
    "severity":"INFO","logger":"SplunkLoggerJson","time":"1620652477.426","thread":"http-nio-8080-exec-1",
    "message":
       {
       "metadata":
          {
           "id":"...",
           "uri":"...",
           "type":"..."
          },
      "customHeaderPropertiesRef":...,
      "logStart":"2021-05-10T11:25:00.013",
      "logEnd":"2021-05-10T11:25:00.236",
      ...,
      "status":"COMPLETED",
      "alternateWebLink":"...",
      "logLevel":"INFO",...
       }
  },
  "sourcetype":"...",
  "source":"..."
}

In this way, it was possible to reference to the timestamp in 'event.message.logStart' as "TIMESSTAMP_FIELDS" attribute of the source-type definition in Splunk.

After we updated to the version 1.9.0, the library produced with the same configurations an event structure as follows:
{
  "alternateWebLink":"...",
  "customHeaderPropertiesRef":...,
  "logEnd":"2021-05-10T11:25:00.236",
  "logLevel":"INFO",...
  "logStart":"2021-05-10T11:25:00.013",
  ...,
  "metadata":
    {
      "id":"...",
      "uri":"...",
      "type":"..."
    },
  "status":"COMPLETED",...
}

Now we need to reference to 'logStart' as "TIMESSTAMP_FIELDS" attribute of the source-type definition in Splunk. And we don't more have the "severity" and "logger" attributes ('source-type' and 'source' attributes have been processed already correctly w/o explicit event content).

Will be this behavior the final one regarding "sending raw events to splunk"?
Do we need to consider any other aspects about the use of "sending raw events to splunk"? We miss a documentation about this special topic.

Thanks a lot.

Best regards

Ilker Yümsek

**Comment by sierralex58** [comment]
It would be interesting to see your current log4j2.xml. Regards Alex

**Comment by yuemsike** [comment]
Hello,

our logback-configuration is as follows:
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>

	<property name="LOGS" value="./logs" />
	
	<appender name="Console"
		class="ch.qos.logback.core.ConsoleAppender">
		<layout class="ch.qos.logback.classic.PatternLayout">
			<Pattern>
				%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable
			</Pattern>
		</layout>
	</appender>

	<Appender name="Splunk_HEC_JSON"
		class="com.splunk.logging.HttpEventCollectorLogbackAppender">
		<url>${SPLUNK_HEC_URL}</url>
		<token>${SPLUNK_HEC_TOKEN}</token>
		<disableCertificateValidation>true</disableCertificateValidation>
		<batch_size_count>1</batch_size_count>
		<sourcetype>ibis:sci:devopsconnector</sourcetype>
		<source>SCPI-DevOps-Center</source>
		<layout class="ch.qos.logback.classic.PatternLayout">
			<pattern>%msg</pattern>
		</layout>
		<type>raw</type>
		<channel>95413756</channel>
	</Appender>
	
	<Appender name="Splunk_HEC_LOG4J"
		class="com.splunk.logging.HttpEventCollectorLogbackAppender">
		<url>${SPLUNK_HEC_URL}</url>
		<token>${SPLUNK_HEC_TOKEN_LOG4J}</token>
		<disableCertificateValidation>true</disableCertificateValidation>
		<batch_size_count>1</batch_size_count>
		<sourcetype>log4j</sourcetype>
		<source>SCPI-DevOps-Center</source>
		<layout class="ch.qos.logback.classic.PatternLayout">
			<pattern>%msg</pattern>
		</layout>
		<type>raw</type>
		<channel>95413756</channel>
	</Appender>

	<appender name="RollingFile"
		class="ch.qos.logback.core.rolling.RollingFileAppender">
		<file>${LOGS}/spring-boot-logger.log</file>
		<encoder
			class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
			<Pattern>%d %p %C{1.} [%t] %m%n</Pattern>
		</encoder>

		<rollingPolicy
			class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			
			<fileNamePattern>${LOGS}/archived/spring-boot-logger-%d{yyyy-MM-dd}.%i.log
			</fileNamePattern>
			<timeBasedFileNamingAndTriggeringPolicy
				class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
				<maxFileSize>10MB</maxFileSize>
			</timeBasedFileNamingAndTriggeringPolicy>
		</rollingPolicy>
	</appender>

	
	<root level="${SCPI_DEVOPS_CONNECTOR_GEN_LOG_LEVEL_CORE:-INFO}">
		<appender-ref ref="RollingFile" />
		<appender-ref ref="Console" />
	</root>

	
	<logger name="com.schaeffler" level="${SCPI_DEVOPS_CONNECTOR_INT_LOG_LEVEL_SERVICE:-INFO}" additivity="false">
		<appender-ref ref="RollingFile" />
		<appender-ref ref="Console" />
	</logger>
	
	
	<logger name="SplunkLoggerJson" level="${SCPI_DEVOPS_CONNECTOR_INT_LOG_LEVEL_SERVICE:-INFO}" additivity="false">
		<appender-ref ref="Splunk_HEC_JSON" />
	</logger>
	
	
	<logger name="SplunkLoggerLog4j" level="${SCPI_DEVOPS_CONNECTOR_INT_LOG_LEVEL_SERVICE:-INFO}" additivity="false">
		<appender-ref ref="Splunk_HEC_LOG4J" />
	</logger>

</configuration>`

This is the variant for the new version (1.9.0) of the library, so you have an additional "channel" tag in the relevant Splunk_HEC* appenders (we have two of them because of the different source-types). In the channel element I cannot identify any relation to the configurations in Splunk and when I let the element empty the library throws an exception and the spring boot application cannot start.

In the variant for 1.8.0 you don't need the channel element.

Regards

Ilker Yümsek

**Comment by bparmar-splunk** [comment]
Hi @yuemsike,
We have recently launched version [v1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5). 
The version which you are using is much more older than what we have now.
We recommend you to update your library version and re-evaluate your use-case.

Please let us know if you face any issue.
Thank you !

**Comment by bparmar-splunk** [comment]
Hi @yuemsike,
We didn't get any updates from you.
We are assuming that the issue has been resolved based on above [comment](https://github.com/splunk/splunk-library-javalogging/issues/177#issuecomment-1225531495).

Closing this issue for now.
Please let us know in case of any further queries.

Thank you.
