### ISSUE TITLE
HttpEventCollectorSender should more easily support overriding

### ISSUE THREAD

**Issue by frkline** [splunk/splunk-library-javalogging#18]
We'd like to enable our application to send custom messages to splunk. The code-security model around HttpEventCollectorSender makes this difficult.
1. Can `HttpEventCollectorSender` be made `public` and non-`final`?
2. Could `HttpEventCollectorSender.serializeEventInfo` be made `protected`?
3. Can `HttpEventCollectorLogbackAppender` support injection of a sender?

Alternatively, please allow for injecting a function for `serializeEventInfo` into the configuration of the appender

**Comment by shakeelmohamed** [comment]
Hi @frkline,

Thanks the suggestions, these all seem like reasonable changes.
We're happy to bring in a pull request to the `develop` branch

**Comment by bparmar-splunk** [comment]
Above [PR#134](https://github.com/splunk/splunk-library-javalogging/pull/134) resolves this issue.
Hence closing this issue.
