### ISSUE TITLE
Artifact 1.9.0 not published on maven central

### ISSUE THREAD

**Issue by ssgtcookie** [splunk/splunk-library-javalogging#180]
Latest version we can grab is version 1.8.0. Can this be updated to version 1.9.0? https://mvnrepository.com/artifact/com.splunk.logging/splunk-library-javalogging

**Comment by ssgtcookie** [comment]
Using that repository is not allowed (read blocked) in my company. We have
a paid corporate licence for splunk.

Op do 20 mei 2021 20:53 schreef Alexandre Masson ***@***.***>:

**Comment by mmoayyed** [comment]
"https://splunk.jfrog.io/splunk/ext-releases-local" is producing 403 errors.

**Comment by lbruun** [comment]
I can certainly browse:

https://splunk.jfrog.io/ui/native/ext-releases-local/com/splunk/logging/splunk-library-javalogging

As per the documentation the artifact is not meant to be on Maven Central but only on Splunk's own Maven repo.

Therefore I think this ticket should be closed. 

You can raise a [feature request](https://github.com/splunk/splunk-library-javalogging/issues/new) if you believe that it is inconvenient that it is not on Maven Central. If your company does not proxy Splunk's own Maven repo then (in most companies) you can manually download from [Splunk's Maven repo](
https://splunk.jfrog.io/ui/native/ext-releases-local/com/splunk/logging/splunk-library-javalogging) and then upload into your company's in-house-hosted third-party Maven repo.

**Comment by lewismc** [comment]
+1 to close.

**Comment by bparmar-splunk** [comment]
This issue is no longer applicable.
Hence closing this issue.
