### ISSUE TITLE
HttpEventCollectorLoggingHandler does not format java.util.logging.LogRecord with parameters 

### ISSUE THREAD

**Issue by SoulRob** [splunk/splunk-library-javalogging#181]
Version of this project you're using: splunk-library-javalogging-1.9.0.jar
Platform version: Windows
Framework version: Java 8

Log records that use [message parameters ](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html#log(java.util.logging.Level,%20java.lang.String,%20java.lang.Object[])) aren't resolved by the publish method

E.G. the following line:
`logger.log(Level.INFO, "Running with config: {0}", cl.getOptionValue("config"));`

Get's sent to splunk as:
`message: Running with config: {0}`

This is because the record.getMessage() (as per the [javadoc](https://docs.oracle.com/javase/7/docs/api/java/util/logging/LogRecord.html#getMessage())) obtains the "raw" log message, before localization or formatting.

```
    public void publish(LogRecord record) {
        this.sender.send(
                record.getLevel().toString(),
                record.getMessage(),
                includeLoggerName ? record.getLoggerName() : null,
                includeThreadName ? String.format(Locale.US, "%d", record.getThreadID()) : null,
                null, // no property map available
                (!includeException || record.getThrown() == null) ? null : record.getThrown().getMessage(),
                null // no marker available
        );
    }
```

To obtain the log message with resolved parameters, it needs formatting via a Formatter. This simple hack fixes the issue:
```
        java.util.logging.Formatter formatter = getFormatter();
        if(formatter == null ){
            formatter = new SimpleFormatter();
        }
        this.sender.send(record.getLevel().toString(),
                formatter.formatMessage(record),
                includeLoggerName ? record.getLoggerName() : null,
                includeThreadName ? String.format(Locale.US, "%d", record.getThreadID()) : null,
                null, // no property map available
                (!includeException || record.getThrown() == null) ? null : record.getThrown().getMessage(),
                null // no marker available
        );
```

**Comment by bparmar-splunk** [comment]
Hi @SoulRob,
Thanks for reaching out !

We have added a formatter in this [commit](https://github.com/splunk/splunk-library-javalogging/commit/8d3f6ee59ec709f5ec5273de1ee020688ebbe89a).
We have executed few tests and are successfully passed.

Hence, we are closing this issue.

Please let us know in case of any further queries.
