### ISSUE TITLE
Delayed time when using AsyncAppender

### ISSUE THREAD

**Issue by johncurrier** [splunk/splunk-library-javalogging#185]
When wrapping com.splunk.logging.HttpEventCollectorLogbackAppender in a ch.qos.logback.classic.AsyncAppender the timestamps that get reported to Splunk are when the event is written instead of when it is logged. Since writing occurs in a background thread that may execute several seconds after the log entry was created Splunk's perspective of when things happened is severely incorrect.

I've branched and created a potential fix off of main (develop, which is specified, doesn't exist?), but am unclear on how to verify my fix. 

My branch: https://github.com/johncurrier/splunk-library-javalogging/tree/Delayed_timestamps_with_AsyncAppender

**Comment by bparmar-splunk** [comment]
Closing this issue as it is fixed in [PR](https://github.com/splunk/splunk-library-javalogging/pull/186).
