### ISSUE TITLE
splunk.jfrog.io is throwing 403 Forbidden

### ISSUE THREAD

**Issue by varenyavv** [splunk/splunk-library-javalogging#187]
Not able to download splunk-library-javalogging library as splunk.jfrog.io is throwing Forbidden 403 error.

* What went wrong:
17:07:24  Execution failed for task ':compileJava'.
17:07:24  [33m> [39mCould not resolve all files for configuration ':compileClasspath'.
17:07:24     [33m> [39mCould not resolve com.splunk.logging:splunk-library-javalogging:1.8.0.
17:07:24       Required by:
17:07:24           project :
17:07:24        [33m> [39mCould not resolve com.splunk.logging:splunk-library-javalogging:1.8.0.
17:07:24           [33m> [39mCould not get resource 'https://splunk.jfrog.io/splunk/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.8.0/splunk-library-javalogging-1.8.0.pom'.
17:07:24              [33m> [39mCould not GET 'https://www.jfrog.com/error?from=splunk.jfrog.io&by=nginx-shared1c'. Received status code 403 from server: Forbidden
17:07:24

**Comment by sunkaiqin** [comment]
Could anyone from the team help resolve this issue and our build system is relying on it? Thanks!

**Comment by fantavlik** [comment]
Investigating now -- I see https://splunk.jfrog.io/splunk/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.8.0/splunk-library-javalogging-1.8.0.pom and all jars under https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.8.0/ appear to be accessible via browser or cURL - I wonder if this was an intermittent issue? I don't see any incidents on https://status.jfrog.io/. Are you still experiencing this issue?

**Comment by sunkaiqin** [comment]
We just checked it works right now. Thanks @fantavlik for the investigation!

**Comment by fantavlik** [comment]
OK great to hear, I'll assume it was a service outage for now, please continue to alert us if you see issues like this in the future.
