### ISSUE TITLE
If message starts with // or #, or surrounded by /* */, it is replaced with a null string.

### ISSUE THREAD

**Issue by larrys** [splunk/splunk-library-javalogging#188]
This is because the code tries to parse the content of the message to see if it is JSON here https://github.com/splunk/splunk-library-javalogging/blob/main/src/main/java/com/splunk/logging/serialization/EventInfoTypeAdapter.java#L36
We should check if the returning object is null, and the message is not null and has data, to then fallback to using the unparsed message.

**Comment by bparmar-splunk** [comment]
Hi @larrys,
Thanks for reaching out !
We are open for the PR to support your use case. We would like to review your use case.

Please let us know, if you have any queries.

**Comment by larrys** [comment]
You can see a "fix" for this (minus unit tests) here: https://github.com/larrys/splunk-library-javalogging/commit/5c905e7cc629560d480584a3531702c0829acaa7

**Comment by bparmar-splunk** [comment]
Hi @larrys,
We are concern about the use case for this specific need.
Could you please share any business use case in which this change is required?
It would help us to make a decision of incorporating this change.

Thank you.

**Comment by larrys** [comment]
I was trying to switch from using a logback server to send logs to, that then got indexed with a UF to using this library to directly talk to Splunk over HEC. I was unable to since it was dropping the log message that happened to start with //, # or was surrounded by /* */.

**Comment by mbukowski-splunk** [comment]
Hi @larrys .
Can you please provide us more details so we can simulate/reproduce this behaviour on our side?
Thanks,
Marcin

**Comment by larrys** [comment]
Just have a log.info statement such as:

```
log.info("#### This is a test ####")
```

With the fix on my PR it will have a log message sent to splunk with the content of that log statement. With the master branch of this repo, it won't, the message will be evaluated as an empty string.

**Comment by larrys** [comment]
You can see https://github.com/splunk/splunk-library-javalogging/commit/d6589567b0c252e7c7a0e7abf31186ca14102da7 for a very simplistic unit test that I was able to throw together. It should be expanded on for other edge cases, being passed to the seralize method.

**Comment by larrys** [comment]
Thanks!
