### ISSUE TITLE
Timestamp event info behavior changed between 1.7.3 and later versions.

### ISSUE THREAD

**Issue by steyng** [splunk/splunk-library-javalogging#197]
Version of this project you're using: 1.10.0
Platform version: Windows 10
Framework version: Java 8
Splunk version: 8.2.1

In version 1.7.3, the event serialization for converting event info into the string for sending to the HEC, included the event info time in the event metadata, i.e.

`this.time = System.currentTimeMillis() / 1000.0;` //system time that the event was logged to the buffer.

This would result in the Splunk event timestamps reflecting values a lot closer to when the original event was actually logged, e.g.

`08/09/2021 20:17:36.000`

See HttpEventCollectorSender.java lines 258 to 267, in particular line 266:

```java
    @SuppressWarnings("unchecked")
    private String serializeEventInfo(HttpEventCollectorEventInfo eventInfo) {
        // create event json content
        //
        // cf: http://dev.splunk.com/view/event-collector/SP-CAAAE6P
        //
        JSONObject event = new JSONObject();
        // event timestamp and metadata
        putIfPresent(event, MetadataTimeTag, String.format(Locale.US, "%.3f", eventInfo.getTime()));
        putIfPresent(event, MetadataHostTag, metadata.get(MetadataHostTag));
```

In versions 1.8.0, 1.9.0 and 1.10.0, the event info time is no longer sent as part of the Splunk metadata by default. As a result the Splunk event timestamps are now logged as the time the event is indexed in Splunk. There may be several seconds between when the original event occurred and the Splunk event log timestamp shows the event being received. The message body now contains the original log event timestamp as generated in 1.7.3.

@johncurrier provided a fix in Issue #185 and pull request #186 which were released in 1.10.0 that ensured the timestamp of the event in the body now reflects the timestamp of the original log event. However, the Splunk metadata timestamp value is still not set in the event header by default.

In pull request #186, @PeterTeunisssen mentioned using the EventHeaderSerializer to fix this oversight. He also mentioned a code change to do the same without the EventHeaderSerializer.

I am not quite sure why the default behavior for logging the Splunk event metadata and message was changed. Would it not have been better to return to using the same defaults as provided in 1.7.3 so that consumers of the library are not surprised by the change in behavior when going to 1.10.0? i.e.

Remove lines 26 to 28 from 1.10.0 of the `EventInfoTypeAdapter` class.

```java
        if (src.getTime() > 0) {
            event.put("time", String.format(Locale.US, "%.3f", src.getTime()));
        }
```

Replace lines 50 to 56 from 1.10.0 of the `HecJsonSerializer` class with

```java
    public String serialize(HttpEventCollectorEventInfo info) {
        Map<String, Object> event;
        if (this.eventHeaderSerializer != null) {
            event = eventHeaderSerializer.serializeEventHeader(info, new HashMap<>(template));
        } else {
            event = new HashMap<>(template);
            event.put("time", String.format(Locale.US, "%.3f", info.getTime()));
        }
```

**Comment by bparmar-splunk** [comment]
Closing this issue as [PR](https://github.com/splunk/splunk-library-javalogging/pull/198) related to this issue is merged.
