### ISSUE TITLE
`HttpEventCollectorLoggingHandler` ignores the formatter option

### ISSUE THREAD

**Issue by asmyers** [splunk/splunk-library-javalogging#204]
The Java `logging.properties` format specifies the ability to add a formatter to a logging handler.  I would like to be able to use the Elastic Common Schema formatter with Splunk to capture information we gather on other systems.

```
com.splunk.logging.HttpEventCollectorLoggingHandler.formatter = co.elastic.logging.jul.EcsFormatter
```

However, the `HttpEventCollectorLoggingHandler` ignores the formatter directive.  JDK implementations, such as [StreamHandler](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.logging/share/classes/java/util/logging/StreamHandler.java#L193) use the formatter to format the message prior to writing it to the underlying writer.

**Comment by bparmar-splunk** [comment]
Hi @asmyers,
Thanks for raising this up !

We have added a support for adding formatter for Java logging.
Please check this [commit](https://github.com/splunk/splunk-library-javalogging/commit/820128b18c61c22bc5bdac6540ba4c8369560946).

We are closing this issue for now.

Please verify with your example and let us know in case of further queries.
Thank you.
