### ISSUE TITLE
How can I use middleware to customize my log message to splunk?

### ISSUE THREAD

**Issue by tamduongp** [splunk/splunk-library-javalogging#206]
Currently my log event is in a json format with **logger**, **message**, **severity**, **thread**, **exception**, and **time.** I find that **logger** doesn't show the actual method (instead, it only show the class), **exception** doesn't show details but only those lines at the top, and **time** is not correct. Fortunately I got my message to log all that information, but now I want to only send the message to splunk and exclude all the other stuffs like logger, exception, etc. I read somewhere that i can use middleware to customize the message to splunk but I'm having a hard time finding documentation on how to use middleware. 
Currently my log look like this in splunk:
`{"severity":"INFO","logger":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener","time":"1633976412.423","thread":"main","message":"2021-10-11 13:20:12.423 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.logMessage - \r\n\r\nError starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.\r\n"}`

Is there a way I can achieve the following? 
`2021-09-15 17:07:58.483 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.logMessage - Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.`

**Comment by bparmar-splunk** [comment]
Hi @tamduongp,
To make use of middleware, please refer this [file](https://github.com/splunk/splunk-library-javalogging/blob/main/src/main/java/com/splunk/logging/HttpEventCollectorResendMiddleware.java#L31).

Also, in log4j.xml file, you can add your FQCN as middleware attribute. Please check [this file](https://github.com/splunk/splunk-library-javalogging/blob/main/src/test/resources/log4j2.xml#L43) for reference.

**Comment by bparmar-splunk** [comment]
Hi @tamduongp,
Since we didn't see any updates from your side. Your issue might have resolved based on above message.

Closing this issue.
Please let us know, if you have any further queries.
