### ISSUE TITLE
slf4j + logback + splunk 6.2.3 - TcpAppender is not working

### ISSUE THREAD

**Issue by alexterman** [splunk/splunk-library-javalogging#21]
I tried following versions: 
logback-classic-1.1.3.jar
logback-core-1.1.3.jar
slf4j-api-1.7.13.jar
splunk-library-javalogging-1.5.0.jar

and also
logback-classic-1.0.13.jar
logback-core-1.0.13.jar
slf4j-api-1.7.5.jar
splunk-library-javalogging-1.5.0.jar

but was not able to see my logs in splunk (I used exact configurations as in README here).
 The run() of the TcpAppender is never called for some reason. 

With log4j 2.1 it is perfectly working, but not with logback.

**Comment by kob-aha** [comment]
It is related to issue #16. I had the same problem and downgrading to logback 1.0.13 solved it.

**Comment by shakeelmohamed** [comment]
Hi @alexterman,

Do you need this relatively soon, or can you work off of the changes from #16 in the `develop` branch?

**Comment by alexterman** [comment]
Hi @shakeelmohamed ,

Thanks for quick response.
I moved to a log4j implementation currently, so no rush.
Once you will release a new version I will take it.

BTW when approximately you are planning that?

**Comment by JonMR** [comment]
What's the plan to get this into a release?

**Comment by glennblock** [comment]
Thanks for reporting this @alexterman. I am looking into how we can get this released.

**Comment by shakeelmohamed** [comment]
Hi folks, we've released v1.5.1. Let us know if that solves your issues!
