### ISSUE TITLE
Error in flush event

### ISSUE THREAD

**Issue by chokdee** [splunk/splunk-library-javalogging#211]
Hi guys
we saw in Dynatrace the following stacktrace from the Splunkappender

`com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403)
com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541)
com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
com.google.gson.JsonParser.parseReader(JsonParser.java:61)
com.google.gson.JsonParser.parseString(JsonParser.java:47)
com.google.gson.JsonParser.parse(JsonParser.java:98)
com.splunk.logging.serialization.EventInfoTypeAdapter.serialize(EventInfoTypeAdapter.java:36)
com.splunk.logging.serialization.EventInfoTypeAdapter.serialize(EventInfoTypeAdapter.java:17)
com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
com.google.gson.Gson.toJson(Gson.java:704)
com.google.gson.Gson.toJson(Gson.java:683)
com.google.gson.Gson.toJson(Gson.java:638)
com.google.gson.Gson.toJson(Gson.java:618)
com.splunk.logging.serialization.HecJsonSerializer.serialize(HecJsonSerializer.java:66)
com.splunk.logging.HttpEventCollectorSender.postEvents(HttpEventCollectorSender.java:361)
com.splunk.logging.HttpEventCollectorMiddleware.postEvents(HttpEventCollectorMiddleware.java:85)
com.splunk.logging.HttpEventCollectorSender.postEventsAsync(HttpEventCollectorSender.java:325)
com.splunk.logging.HttpEventCollectorSender.flush(HttpEventCollectorSender.java:202)
com.splunk.logging.HttpEventCollectorSender.send(HttpEventCollectorSender.java:185)
com.splunk.logging.HttpEventCollectorLog4jAppender.append(HttpEventCollectorLog4jAppender.java:235)
org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:540)
org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:498)
org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:481)
org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:456)
org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
org.apache.logging.log4j.core.Logger.log(Logger.java:161)
org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2022)
org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1875)
org.apache.logging.slf4j.Log4jLogger.warn(Log4jLogger.java:239)
`

Maybe it will help you to find the issue

**Comment by bparmar-splunk** [comment]
Hi @chokdee,
It seems there are two or multiple version of gson jars exist in your environment. And sometimes, classloader loads old version of gson jar and hence you are facing this issue.
We recommend you to please update / remove old versions and also update your splunk logging lib to [latest version](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5).

Please let us know, if you still face any issue.

**Comment by bparmar-splunk** [comment]
HI @chokdee,
Since there is no such update from your side regarding this issue.
We are considering it as done for now and closing this issue.

Let us know in case you face this error again.
