### ISSUE TITLE
Sending raw Java Throwable

### ISSUE THREAD

**Issue by UnitedMarsupials** [splunk/splunk-library-javalogging#220]
The `HttpEventCollectorSender.send()` allows callers to include the exception information, but that info must already be a String.

It'd be a lot nicer, if the actual Java `Throwable` could be passed -- so that it could be serialized into JSON and then properly rendered by Splunk GUI:
```json
 {"detailMessage":"/ by zero","stackTrace":[{"declaringClass":"test","methodName":"main","fileName":"test.java","lineNumber":9}]} 
```
I tried converting the string into JSON myself -- in my own code -- and passing the resulting string to `send()`:
```java
		String exception = null;

		if (excToJson != null) {
			ThrowableInformation exc = event.getThrowableInformation();
			if (exc != null) {
				Throwable t = exc.getThrowable();
				if (includeExcStack) {
					LogLog.debug("Adding stack trace");
					t.setStackTrace(t.getStackTrace());
				}
				exception = excToJson.toJson(t);
			}
		}
...
		this.sender.send(
		    event.timeStamp,
		    event.getLevel().toString(),
		    message,
		    includeLoggerName ? event.getLoggerName() : null,
		    includeThreadName ? event.getThreadName() : null,
		    includeMDC ? event.getProperties() : null,
		    exception, /* JSON-formatted text with the exception - or null */
		    (Serializable)null
		);
```

but that ended up reformatted, with all characters special to JSON -- escaped. I think, a separate `send`-method is warranted, one where the `exception` variable is of type `Throwable`, rather than `String`.

**Comment by bparmar-splunk** [comment]
Hi @UnitedMarsupials,
Thanks for bringing this up .

We will consider your suggestion by adding a Java throwable in send method.

**Comment by bparmar-splunk** [comment]
Hi @UnitedMarsupials,
We would like to update you that we have pushed relevant changes to resolve this issue. ([changes](https://github.com/splunk/splunk-library-javalogging/commit/6a94f18eeb4b1987ba7acd0f8a47412fd4077c45))

Please let us know in case of any queries.

Thank you.

**Comment by bparmar-splunk** [comment]
Hi @UnitedMarsupials,
We are closing this ticket as the changes are already been pushed to repo.

Please let us know in case of further queries.
Thank you.
