### ISSUE TITLE
Add support for host tag

### ISSUE THREAD

**Issue by afinkenstadt** [splunk/splunk-library-javalogging#24]
Pull request to come.
CLA pending legal review.

**Comment by PedroAlvarado** [comment]
I'm currently integrating the http collector with our production application and I ran into this issue. I'd be great to see this pushed 1.5.2 soon.

**Comment by afinkenstadt** [comment]
CLA has been signed.  I also emailed devinfo@splunk.com to let them know the three cumulative pull requests #25 #28 and #29 can now to integrated.

**Comment by PedroAlvarado** [comment]
@shakeelmohamed Can you help us get 1.5.2 out with the changes made by @afinkenstadt? We would greatly appreciate your attention to this.

**Comment by shakeelmohamed** [comment]
@PedroAlvarado @afinkenstadt we will look into it, thanks for raising the issue and letting us know

**Comment by shakeelmohamed** [comment]
We've released v1.5.2, thanks again for your work here @afinkenstadt!
