### ISSUE TITLE
Bump Log4j version to 2.17.1 as per latest recommendation

### ISSUE THREAD

**Issue by avulachandrashekar** [splunk/splunk-library-javalogging#243]
Bump Log4j version to 2.17.1 as per latest recommendation

**Comment by bparmar-splunk** [comment]
Hi @avulachandrashekar,
Log4j version is upgraded to v2.17.2 in [new released version](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5).

Hence, closing this issue.
