### ISSUE TITLE
Please add a Git tag for version 1.5.4

### ISSUE THREAD

**Issue by sschuberth** [splunk/splunk-library-javalogging#244]
The source code for release 1.5.4 is not tagged in Git. Could you please add a tag (like there is one for release 1.5.3)?

**Comment by bparmar-splunk** [comment]
HI @sschuberth,
Do you still need the tag of version 1.5.4?
As currently, we have updated till version 1.11.5. We would recommend to update it to version [1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5).

**Comment by sschuberth** [comment]
> Do you still need the tag of version 1.5.4?

Yes please, as it's partly out of our control which version is being used.

> As currently, we have updated till version 1.11.5.

I see, but still having *any* missing tags from 1.5.4 to 1.11.5 added would be highly appreciated for consistency and provenance reasons.

**Comment by bparmar-splunk** [comment]
Hi @sschuberth,
We have created a tag of [v1.5.4](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.5.4).

Closing this issue.
