### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by xchang1226** [splunk/splunk-library-javalogging#245]
Can you please provide the next release date? We need a release that contains the fix for https://github.com/splunk/splunk-library-javalogging/issues/197. Thanks.

**Comment by stokpop** [comment]
I am curious too, we are waiting for multiple fixes that are already merged. Is there a road map for the next release?

**Comment by bparmar-splunk** [comment]
New version ([1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5)) is successfully released.

Closing this issue.
