### ISSUE TITLE
Not able to use proxy for HttpEventCollectorLogbackAppender

### ISSUE THREAD

**Issue by tamduongp** [splunk/splunk-library-javalogging#250]
Our team is having a problem sending logs to splunk cloud since it requires proxy. This library allows users to use system properties but the systemwide setting in our production environment are "no proxy" and this rule can not be change. It would be great if the proxy settings could be passed into the HttpEventCollectorLogbackAppender.

**Comment by bparmar-splunk** [comment]
Hi @tamduongp,
Could you please elaborate more on your issue with a snippet/example ?
It would help us in reproducing / troubleshooting this issue.

**Comment by bparmar-splunk** [comment]
Hi @tamduongp,
We did not hear anything from you.

We are closing this issue for now.
Let us know if you have any questions.

Thank you.
