### ISSUE TITLE
why do you use Splunk

### ISSUE THREAD

**Issue by fizz12344321** [splunk/splunk-library-javalogging#255]
Hi, i am reading your repository and i love it, but i have a question, why do you use Splunk ? Can u tell me your purpose, the pros and cons of Splunk, why don't u use Micrometer, Prometheus, grafana. Thank u so much

**Comment by mbukowski-splunk** [comment]
Hi,
Comparing to other tools are more marketing thing, but I can share with you what are the key points from my experience:
-> Splunk is great searchable database that you can monitor and visualize and organize your data.
-> Splunk is a integrated platform that you have hosted data collection, monitoring, visualization, analysis and storage service all in one place
-> users are super happy with the support we provide
-> there are tones of TAs available for free which are super helpful for the integration with other software
-> awesome querying language SPL(2)
-> very efficient search
-> mappings to CIM for complex envs

Hope that helps!

**Comment by bparmar-splunk** [comment]
Hi @fizz12344321,
Hope this [message](https://github.com/splunk/splunk-library-javalogging/issues/255#issuecomment-1190005739) answers your question.

Hence, closing this issue.
Please let us know in case of any further queries.
