### ISSUE TITLE
Add fuller support for splunk Event Collector

### ISSUE THREAD

**Issue by afinkenstadt** [splunk/splunk-library-javalogging#26]
Do you have any suggestions on how much of the Docker Splunk Logger Driver to add to the Java logging facility for this project?

In particular:

- [X] How to map the [MDC](http://logback.qos.ch/manual/mdc.html) `Map<String,String>` to something on Splunk
- [X] Whether to log the `getThreadName()`, `getLoggerName()`, and `hasCallerData()` → `getCallerData()` information, and if so, where?

(Yes, I'll be doing this work.)

**Comment by afinkenstadt** [comment]
Implemented in #28

**Comment by shakeelmohamed** [comment]
@afinkenstadt I've opened a review in #29, please take a look. We cannot release your changes with the new dependency for all users on logback.

**Comment by shakeelmohamed** [comment]
We've released v1.5.2, thanks again for your work here @afinkenstadt!
