### ISSUE TITLE
is there any repo like splunk-library-gologging, to support java lang. thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [splunk/splunk-library-javalogging#283]
is there any repo like splunk-library-gologging, to support java lang. thanks.

**Comment by johnzheng1975** [comment]
Any response? Thanks.

**Comment by tdhellmann** [comment]
Hi John,

Sorry for the delay! Is this what you're looking for?

https://docs.splunk.com/observability/en/gdi/get-data-in/application/go/instrumentation/instrument-go-application.html

Best,

-Tedd

---
Dr. Theodore D. Hellmann
Senior Principal Product Manager
App Platform Group
