### ISSUE TITLE
Log4j PatternLayout not honored

### ISSUE THREAD

**Issue by SafTheCodeNinja** [splunk/splunk-library-javalogging#32]
The log4j PatternLayout of "%m" is always sent via `HttpEventCollectorLog4jAppender`
It does not use the layout object to format the message.

Version: 1.5.1
Platform: Windows 7
Framework version: Java 6,7,8
Splunk version: 6.3.3

**Comment by tdhellmann** [comment]
Just wanted to pop in to say we're working on a fix for this issue.

**Comment by dan1** [comment]
This appears to have been addressed by https://github.com/splunk/splunk-library-javalogging/commit/6034d76a57563ada409f777c7f43d586f99e1b0b

Thanks @SafTheCodeNinja!
