### ISSUE TITLE
Upgrade to work with logback 1.1.7

### ISSUE THREAD

**Issue by sbillings** [splunk/splunk-library-javalogging#36]
I recently upgraded to logback 1.1.7 and my application stopped logging to Splunk.  Once I went back to logback 1.1.6 it started working again.  Can we get the library to support logback 1.1.7 please?

**Comment by alphahelix00** [comment]
Has anyone tested this with latest logback version 1.2.1?

**Comment by tdhellmann** [comment]
Thanks for the reminder - we're taking a look.

**Comment by kvnxiao** [comment]
@tdhellmann that's a bit late for a "reminder", haha. Make sure it works with up to logback 1.2.3 now I guess?

**Comment by tdhellmann** [comment]
Definitely on the late side, sorry. We're definitely going to investigate up to 1.2.3.

**Comment by akauppi** [comment]
Logback is at 1.2.3 and it's 2020. Can this issue be closed, or is there something I should be aware of?

Please, please clean up aging issues. They consume time from visitors like me.
