### ISSUE TITLE
Log throwable stack traces in addition to the message

### ISSUE THREAD

**Issue by dspasojevic** [splunk/splunk-library-javalogging#39]
Hi,

Do you think that it would be desirable to support logging stack traces for throwables in addition to the message? Perhaps gated behind a configuration flag. This functionality is supported by structured logging appenders for other products.

If it sounds like a useful feature, happy to put together a PR.

Thanks,
-Dan

**Comment by shakeelmohamed** [comment]
Hi @dspasojevic,

We're open to a pull request as long as the default configuration is sane.
Thanks for the suggestion!

**Comment by dspasojevic** [comment]
Great @shakeelmohamed .

I'm updating the tests for the new functionality. The `*FunctionalTests` that use the `TcpAppender` fail for me. I think that this is because the `TCPAppender` and `Util#readLineFromPort` use the default charset for their Input / Output streams. My system's default charset can not encode the characters used for the test message.

Should the `TcpAppender` be using the default charset?

**Comment by thiagoteichmann** [comment]
Guys, why this code wasn't merged yet? Is there some critical pending? I would like to use this functionality, because not being able to log the stacktrace into Splunk is really bad.

**Comment by tdhellmann** [comment]
Thanks for the reminder - we're taking a look.

**Comment by smgn** [comment]
It think this is still relevant three years later. I send in json format, have a layout format as `<pattern>%msg</pattern>` and still get a stacktrace appended to the message. Even though there is a separate `exception` field now.

**Comment by lbruun** [comment]
The problem really exists mainly for JUL. For Log4j the default `Pattern` will actually append the stack trace- if exists - as part of the message text itself. Hence this library will receive a message text which is very long in such case. In short:  For Log4j you'll actually get the stack trace as @smgn points out.

But for JUL?  Not so. As it stands - correct me if wrong - the SDK provides no way that you can forward the Throwable from the JUL logging event into Splunk HEC. Needless to say this is not an acceptable situation.

How to fix?
I think the most correct solution would be to have the Throwable as part of what is sent to the event serializer. This way, the serializer (which the user can custom create) can decide what to do with it. 

(I haven't investigated the current status for Logback)

**Comment by bparmar-splunk** [comment]
Hi @dspasojevic,
We have enhanced support for sending exception details in events. Priorly it was just message, but we have changed it to send details of exception. Please check this [commit](https://github.com/splunk/splunk-library-javalogging/commit/27f862d143457f9be16f7228d7d403a409d4f3e5).

This might resolve your issue.

Please let us know in case of further queries.
Thank you.

**Comment by dspasojevic** [comment]
Feel free to close this 2016 issue @bparmar-splunk, I haven't used Splunk for a fair few years.

**Comment by bparmar-splunk** [comment]
@dspasojevic,
Thank you for your reply.

Closing this issue.
