### ISSUE TITLE
Logging breaks when multiple TcpAppenders are configured

### ISSUE THREAD

**Issue by cbroglie** [splunk/splunk-library-javalogging#42]
I am trying to configure 2 TcpAppender instances b/c I need to send data to 2 different source types (an error log and a trace log). If I configure either 1 of the 2 appenders, I see data flowing for that source type. But if I configure both, nothing makes it to Splunk.

Here is a minimal working logback.xml file:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d %m%n</pattern>
            <charset>utf8</charset>
        </encoder>
    </appender>
    <appender name="SPLUNK_ERROR" class="com.splunk.logging.TcpAppender">
        <RemoteHost>127.0.0.1</RemoteHost>
        <Port>5000</Port>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d %m%n</pattern>
        </layout>
    </appender>
    <root level="INFO">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="SPLUNK_ERROR" />
    </root>
</configuration>
```

And here is a failing example:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d %m%n</pattern>
            <charset>utf8</charset>
        </encoder>
    </appender>
    <appender name="SPLUNK_ERROR" class="com.splunk.logging.TcpAppender">
        <RemoteHost>127.0.0.1</RemoteHost>
        <Port>5000</Port>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d %m%n</pattern>
        </layout>
    </appender>
    <appender name="SPLUNK_TRACE" class="com.splunk.logging.TcpAppender">
        <RemoteHost>127.0.0.1</RemoteHost>
        <Port>5001</Port>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d %m%n</pattern>
        </layout>
    </appender>
    <root level="INFO">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="SPLUNK_ERROR" />
    </root>
</configuration>
```

**Comment by cbroglie** [comment]
The reason this is happening is b/c after submitting the socket task [here](https://github.com/splunk/splunk-library-javalogging/blob/master/src/main/java/com/splunk/logging/TcpAppender.java#L94), an `InterruptedException` is thrown and it breaks out of the loop [here](https://github.com/splunk/splunk-library-javalogging/blob/master/src/main/java/com/splunk/logging/TcpAppender.java#L129).

I suspect this is related to the use of the `ScheduledExecutorService` returned by `getContext().getExecutorService()`, since it is only sized to run 2 threads (it ends up calling into  [ExecutorServiceUtil. newScheduledExecutorService](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/util/ExecutorServiceUtil.java#L52), and the value of `CoreConstants.SCHEDULED_EXECUTOR_POOL_SIZE` is 2). Using a standalone thread pool for executing `TcpAppender.run` appears to fix the issue.

**Comment by skylasam** [comment]
Thanks for the contribution. PR merged.
