### ISSUE TITLE
Support for HEC raw endpoint

### ISSUE THREAD

**Issue by inspired** [splunk/splunk-library-javalogging#44]
It would be neat if this also supported the HTTP Event Collector raw endpoint using parameterized values for sourcetype, host, index and source through the URL query as well as the channel ID.

See http://dev.splunk.com/view/event-collector/SP-CAAAE8Y

I have a client using Logback asking for this. They'd like to send properly formatted logs out of their Docker/Openshift env without going through the openshift stdout logs that make the logs look like gibberish.

**Comment by shakeelmohamed** [comment]
Thanks @inspired, this is something we'd love to see but it will require a non-trivial engineering effort. That said, we are open to a pull request

**Comment by dan1** [comment]
https://github.com/splunk/splunk-library-javalogging/pull/75

This a port of https://github.com/splunk/splunk-library-javalogging/pull/58
