### ISSUE TITLE
Not work with tomcat 8

### ISSUE THREAD

**Issue by plttlqh** [splunk/splunk-library-javalogging#46]
Hi guys,

I had a problem when upgrade to tomcat 8. HttpEventCollectorLogbackAppender was not contruct but on tomcat 7 It does.

Thanks,
Ha Le

**Comment by shakeelmohamed** [comment]
Hi @plttlqh,

We'll need a bit more information in order to help

**Comment by plttlqh** [comment]
My application is spring mvc, imported logback, slf4j which run on tomcat7, jdk 8 then the application send a message to splunk server. Other way, I only changed tomcat 8 then It not worked. I have no idea.

**Comment by shakeelmohamed** [comment]
Thanks @plttlqh, I'm not entirely sure what the issue is. How urgently do you need this looked at?

**Comment by plttlqh** [comment]
thank @shakeelmohamed, It's not urgent for my team at all. I'm researching for my team, we can wait. :). I can see how convenient of using Splunk :)

**Comment by tdhellmann** [comment]
We don't really have the information necessary to debug this - I'm going to close the issue out, but feel free to come back with additional detail if you are still experiencing this issue.
