### ISSUE TITLE
Json message not handled correctly in HttpEventCollectorLogbackAppender

### ISSUE THREAD

**Issue by nickydu** [splunk/splunk-library-javalogging#48]
I met some issues and hope someone can help!

I'm currently working on a project and would like to push Json message to splunk, but seems like it doesn't get extracted correctly when doing "postEvents" in HttpEventCollectorSender.class. I've noticed in serializeEventInfo it returns event.toString(). I think this ruined the Json message because it treat this message as string and escape all the '{', '}', '"', etc. Please let me know if there is anyway to treat it a Json message in "event"."message", thanks!!!

**Comment by nickydu** [comment]
Sorry, forgot to mention, the version I use is 1.5.0. 

Many thanks!

**Comment by ajaydeshwal** [comment]
Hi @nickydu . I was facing the same problem while using the http logback appender. I have fixed this issue in my fork by introducing a property to set message mime-type to handle log message correctly. Following is the link to commit changes: 
https://github.com/ajaydeshwal/splunk-library-javalogging/commit/1a77f0c093955be66007654e1bc6dc09d6c2541f

I will write test cases around the changes and submit a PR for review. Please feel free to try the changes in your env. You need to add a property `<messageMimeType>` with value `json` in your logback appender configuration. Sample:

```xml
<appender name="splunkHttp" class="com.splunk.logging.HttpEventCollectorLogbackAppender">
	<url>${lsplunk.http.url}</url>
	<token>${splunk.http.token}</token>
	<source>${splunk.source}</source>
	<host>${splunk.httpevent.listener.host}</host>
	<messageMimeType>json</messageMimeType>
	<disableCertificateValidation>${splunk.cert.disable-validattion}</disableCertificateValidation>
	<layout class="ch.qos.logback.classic.PatternLayout">
	    <pattern>%message%rootException</pattern>
	</layout>
</appender>
```

**Comment by ajaydeshwal** [comment]
Submitted a PR that fixes it. https://github.com/splunk/splunk-library-javalogging/pull/50

**Comment by snickers2029** [comment]
#70

**Comment by snickers2029** [comment]
#70 has been merged

**Comment by ajaydeshwal** [comment]
Thanks, @snickers2029

**Comment by peteryao2017** [comment]
@ajaydeshwal  I am facing the same issue although I switched to the latest version and added the property as:
        <messageFormat>json</messageFormat>
With a logback statement:
      JsonNode jsonObject = objectMapper.valueToTree(fields);
      log.info("jsonObject {}",jsonObject);
Or:
log.info("result:{}", value("fields", fields));

From the Console appender, it looks ok,
Thanks,
Peter

**Comment by ajaydeshwal** [comment]
@peteryao2017 The message body must be valid JSON string for the parsing to work. You are appending the word "jsonObject" to the object string representation which becomes an invalid JSON structure.

 In your example following should work:

final String jsonString = objectMapper.writeValueAsString(jsonNode);
log.info(jsonString);
