### ISSUE TITLE
SplunkCimLogEvent.toString() is not parsable by Splunk

### ISSUE THREAD

**Issue by fovea1959** [splunk/splunk-library-javalogging#55]
If you put the output of SplunkCimLogEvent.toString() into a file and have Splunk parse the file, it is parsed incorrectly.

    SplunkCimLogEvent e = new SplunkCimLogEvent("name", "id");
    e.addField("username",  "Douglas E Wegscheid");
    System.out.println(e.toString());

yields

    "name=name" "event_id=id" "username=Douglas E Wegscheid"

Splunk parses the username field as "Douglas".

Removing line 133

    key = key.replaceAll("\"", "\\\\\"");

and changing line 136 to 

    output.append(key + KVDELIM + QUOTE + value + QUOTE);

Output is now

    name="name" event_id="id" username="Douglas E Wegscheid"

which is parsed by Splunk correctly.

Still have the issue of how to correctly quote the key names with spaces or quotes in them, but that is less severe than this issue!

**Comment by tdhellmann** [comment]
Thanks for reaching out - we'll take a look

**Comment by matt-snider** [comment]
Hi @tdhellmann also having this issue. I assumed it would just be a matter of configuration in Splunk - it would surprise me for the official library to be broken for 4 years like that. Is that the case or should values with spaces really *only* be written `key="a value"`?

**Comment by bparmar-splunk** [comment]
@fovea1959,
Changes suggested by you has been pushed to current working branch. Check this [commit](https://github.com/splunk/splunk-library-javalogging/commit/97cc063fd57a5ed3f518c8b6cf2b29fc608edfc5).

@matt-snider, the value which you have mentioned will be written as is. `key="value with whitespace"`

Closing this issue for now.
Please let us know, in case of any further queries.

Thank you.
