### ISSUE TITLE
log4j setup example needs documenting

### ISSUE THREAD

**Issue by rszabo50** [splunk/splunk-library-javalogging#56]
Hi I am trying to make use of the log4j appender that is present in the code but the documentation in the readme file make no reference to it, and does not describe its usage.

The information is present in the test resources directory but it should have an update in the readme file.

**Comment by shakeelmohamed** [comment]
Hi @rszabo50,

Thanks for your concern, we have some external docs outside the repo: http://dev.splunk.com/view/splunk-logging-java/SP-CAAAE7M
We have filed an issue internally to update the readme with setup information, thanks for your patience.

**Comment by akauppi** [comment]
2 years, 3 months and some

**Comment by shakeelmohamed** [comment]
This documentations is available on dev.splunk.com, closing this issue as we will not maintain docs multiple places: https://dev.splunk.com/enterprise/docs/java/logging-java/howtouseloggingjava/enableloghttpjava#Configure-Log4j-2
