### ISSUE TITLE
Impossible to add a header for *Splunk-Request-Channel*

### ISSUE THREAD

**Issue by joseblas** [splunk/splunk-library-javalogging#57]
Make available the option to use collection/raw within the client.

Version of this project you're using: 1.5.3
Platform version: Mac OS / Ubuntu (AWS)
Framework version: Java 8 / Play Framework 2.6
Splunk version: 6.6.3

**Comment by tdhellmann** [comment]
Just chiming in to say we're working on integrating a fix for this
