### ISSUE TITLE
Apache HttpClient is too old to setup Expiry date

### ISSUE THREAD

**Issue by alvindaiyan** [splunk/splunk-library-javalogging#60]
I go the error when integrating with Springboot 1.5.9.RELEASE.
The WARN message are:

o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "Set-Cookie: session_id_8000=8c8aab366443380e3f5c8473fa0513bf62533df4; expires=Thu, 01 Feb 2018 00:34:43 GMT; httponly; Path=/". Invalid 'expires' attribute: Thu, 01 Feb 2018 00:34:43 GMT

this is caused by a known apache  [bug](https://issues.apache.org/jira/browse/HTTPCLIENT-1077)

**Comment by tdhellmann** [comment]
Fix for this has been merged
