### ISSUE TITLE
ReconfigureOnChangeTask not working due to setCorePoolSize on 0

### ISSUE THREAD

**Issue by mmihael** [splunk/splunk-library-javalogging#65]
Logback exposes an option to automatically reload configuration file upon modification.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true"  scanPeriod="5 seconds" debug="true">

    <appender name="SPLUNK" class="com.splunk.logging.TcpAppender">
        <RemoteHost>127.0.0.1</RemoteHost>
        <Port>15000</Port>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%thread %level: %msg%n</pattern>
        </layout>
    </appender>

    <root level="INFO">
        <appender-ref ref="SPLUNK" />
    </root>

</configuration>
```

Note the scan and scanPeriod attributes on configuration node. 
Logback internally creates ReconfigureOnChangeTask which is running on context's executor service.
Problem is that in TcpAppender.java, pool size of that executor service is set to 0 which will also disable ReconfigureOnChangeTask.
```java
ExecutorService service = this.getContext().getExecutorService();
if (service instanceof ThreadPoolExecutor) {
    ((ThreadPoolExecutor) service).setCorePoolSize(0);
}
```

**Comment by shakeelmohamed** [comment]
Thanks @mmihael, we have a related issue (#66). We plan to address both with a similar fix, thanks for your patience.

**Comment by bparmar-splunk** [comment]
This issue is already been fixed as per this [comment](https://github.com/splunk/splunk-library-javalogging/issues/66#issuecomment-589219660).

Hence closing this issue.
