### ISSUE TITLE
Make the splunk libary an OSGi bundle

### ISSUE THREAD

**Issue by cschneider** [splunk/splunk-library-javalogging#67]
We would like to use the splunk appenders in OSGi. To be installed in OSGi the library should be an OSGi bundle.

This is quite easy to achieve by adding the bnd-maven-plugin and some hints in form of a bnd.bnd file. This will not disturb usage in other environments as it simply add a few values to the Manifest.
It should also not cause maintenance costs as all package versions are automatically calculated.

I will create a PR to solve this.

**Comment by tdhellmann** [comment]
We've merged #68 to the develop branch.
