### ISSUE TITLE
Unable to override time sent to Splunk using com.splunk.logging.HttpEventCollectorLogbackAppender

### ISSUE THREAD

**Issue by alekksi** [splunk/splunk-library-javalogging#71]
Hi all,

I'm unable to override any of the root-level JSON fields in the mssages that are being sent to Splunk.

Example:
```
<appender name="SPLUNK" class="com.splunk.logging.HttpEventCollectorLogbackAppender">
	<url>https://testserver:8088</url>
	<token>mytoken</token>
	<index>test_db</index>
	<sourcetype>test_data</sourcetype>
	<disableCertificateValidation>true</disableCertificateValidation>
	<layout class="ch.qos.logback.classic.PatternLayout">
		<pattern>%msg</pattern>
	</layout>
</appender>
```

Did a thing that looks like this:
```
Logger splunk = LoggerFactory.getLogger("SPLUNK");
splunk.info("this is my event message")
```

Which of course turns out looking like this:
```
{"severity":"INFO","logger":"SPLUNK","thread":"splunkHandler","message":"this is my event message"}
```

No matter what I do, I can't add "time":"123456789" to the above. Is there a method or some configuration that is missing from here? Splunk is refusing to play ball unless it's a root-level field.

Thanks!

**Comment by tdhellmann** [comment]
Thanks for reporting this issue - we'll take a look. Sorry for the delayed response.

**Comment by bparmar-splunk** [comment]
@alekksi,
This issue might have been resolved as per the PR mentioned above.

Closing this issue.
Please let us know, in case of further queries.
Thank you.
