### ISSUE TITLE
Library is published in Spring Plugins / Spring Libraries

### ISSUE THREAD

**Issue by jihor** [splunk/splunk-library-javalogging#78]
In Maven Repository, this library is published in Spring Plugins / Spring Libraries repo, while it should probably be published in Central, because it has nothing Spring-specific.

**Comment by tdhellmann** [comment]
Hi @jihor - we don't publish to MvnRepository as part of our release process for the Java Logging Library, so I'm not sure we have the power to make this change. I'll look into this a bit more to see what's going on.
