### ISSUE TITLE
messageFormat not working for text enum

### ISSUE THREAD

**Issue by bharathrajbk** [splunk/splunk-library-javalogging#79]
Hi,

I am using <messageFormat>text</messageFormat> which otherwise is default anyway.

However, I see logs appearing in splunk in a json format.

Can someone please help?

**Comment by tdhellmann** [comment]
@bharathrajbk - I believe that messageFormat can only impact the format inside the payload - not the entire event. Would you be able to provide an example of what you're experiencing so I can confirm that this is the case?

**Comment by izrobin** [comment]
I had to download the sourcecode to find this, but if you set `<type>raw</type>` on your logger adapter, you'll get it raw.

**Comment by tdhellmann** [comment]
We should have a fix for sending events to HEC Raw in #75 in the develop branch, but I'm not sure if that's specifically what you're asking for. Can you confirm that this isn't addressing your issue?

**Comment by izrobin** [comment]
Yes can confirm. By using the "raw" type, you still get the event posted as json. This is because `HttpEventCollectorSender` always serializes it as json

**Comment by bharathrajbk** [comment]
Agree with @izrobin . Please help provide a fix for this.

**Comment by kvaga** [comment]
Hi all!
 Can anybody tell me when this issue will be resolved? It's so annoying to don't have even any opportunity to change the format to a plain text!

**Comment by izrobin** [comment]
@kvaga You can now do it thanks to #83 , please have a look 👍
