### ISSUE TITLE
TcpAppender: getCallerData() should not be called by default

### ISSUE THREAD

**Issue by lbeuster** [splunk/splunk-library-javalogging#8]
Hi, 
logEvent.getCallerData() is now called by default. Since this is an expensive operation (new Throwable().getStackTrace() is invoked) it should be made configurable via a boolean property in the appender: includeCallerData (see logback:SocketAppender). With false as default.

Thx
Lars

**Comment by shakeelmohamed** [comment]
Hi @lbeuster,

Sorry for the slow response here. This seems like a reasonable change, we will look into this for the next release.

**Comment by tdhellmann** [comment]
This should be fixed in a prior release.
