### ISSUE TITLE
No way to configuring the http.socket.timeout and http.connection.timeout on the HttpClient

### ISSUE THREAD

**Issue by mihailnenov** [splunk/splunk-library-javalogging#81]
https://github.com/splunk/splunk-library-javalogging/blob/116d430cd2f7176d8e7439059131edc71d88336d/src/main/java/com/splunk/logging/HttpEventCollectorSender.java#L324

Hello, 
I think while creating a RequestConfig custom object system properties should be used to configure all the possible parameters of the configuration, or at least the timeout value. Another option will be to make the timeout values configurable on the appender (XML).  

Regards,
Mihail

**Comment by shakeelmohamed** [comment]
Thanks for the suggestion @mihailnenov, feel free to make a pull request for the XML config changes

**Comment by mihailnenov** [comment]
Ok, I will do it soon!

regards,
 Mihail

**Comment by mihailnenov** [comment]
Hi, 
Can you please add me to the project, so that I can create a branch I push my  changes?
I also can see there is a pull request #72 , which is kind of doing the same thing but also configuring the connections pool size, is this one going to be merged?

Thanks,
Mihail

**Comment by shakeelmohamed** [comment]
@mihailnenov we accept contributions through the GitHub fork and pull request workflow. You can see this doc for additional instructions if needed - https://help.github.com/articles/creating-a-pull-request/. If you're making a PR, please target the develop branch.

#72 has some merge conflicts, so even if we accepted that we'd have to do some work before merging it in.

**Comment by mihailnenov** [comment]
Thanks for your clarification!
I've just created the PR #82. 

regarads,
Mihail

**Comment by bparmar-splunk** [comment]
Hi @mihailnenov,
We have making use of OkHttp library and we have also configured timeout parameters for better optimisation.
We would recommend to update the logging library version to [1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5).

Closing this issue.
