### ISSUE TITLE
HttpEventCollectorLogbackAppender not flushing buffer on stop

### ISSUE THREAD

**Issue by trevor-martin** [splunk/splunk-library-javalogging#87]
The buffer is not flushing when the stop function is being called. This is happening on our lambdas in aws. The fix has already been made in the HttpEventCollectorLog4jAppender. Here is a link to the associated pull request https://github.com/splunk/splunk-library-javalogging/commit/109c71b5902bec2ea2bf377fbd6457a84ea4c835 . It should only be a matter of changing this.sender.flush() to this.sender.close() since the other code is already in place.

**Comment by tdhellmann** [comment]
Hey @trevor-martin - thanks for catching that! We'll work on an update for that.

**Comment by dan1** [comment]
This should be resolved now.  Thx @trevor-martin for the fix.  https://github.com/splunk/splunk-library-javalogging/pull/93
