### ISSUE TITLE
Version 1.6.2 changes event format

### ISSUE THREAD

**Issue by laenzlinger** [splunk/splunk-library-javalogging#95]
With the introduction of the EventBodySerializer the format of the data sent to splunk has changed.

With 1.6.0:
```
{
    "time": 1437522387,
    "host": "dataserver992.example.com",
    "source": "testapp",
    "event": { 
        "message": "Something happened",
        "severity": "INFO"
    }
}
```

With 1.6.2:
```
{
  "host": "dataserver992.example.com",
  "time": "1545162035.942",
  "source": "testapp",
  "event": "{\"severity\":\"DEBUG\", \"message\": \"Something happened\"}"
}
```

According to the [splunk documentation](http://dev.splunk.com/view/event-collector/SP-CAAAE6P), the format of 1.6.0 was the correct.
Can Splunk handle the new format correctly?

**Comment by akauppi** [comment]
Is this still something I should be concerned about?

**Comment by fantavlik** [comment]
The time format is correct in 1.6.2 and later according to the most recent HTTP Event collector docs: https://docs.splunk.com/Documentation/Splunk/8.0.2/Data/FormateventsforHTTPEventCollector#Event_metadata 
> The event time. The default time format is epoch time format, in the format \<sec\>.\<ms\>. For example, 1433188255.500 indicates 1433188255 seconds and 500 milliseconds after epoch, or Monday, June 1, 2015, at 7:50:55 PM GMT.

The docs may have been slower to update than the SDK implementation but the current implementation should be correct, please re-open if you have any different interpretation.
